{
  "language": "node_js",
  "node_js": "8",
  "script": [
    "npm run lint",
    "npm run build",
    "npm run test",
  ],
  "install": [
    "npm ci",
  ],
  "services": [
    "redis-server",
  ],
}